# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Day11-汽车之家' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Day11-汽车之家
  pod 'AFNetworking'
  pod 'BlocksKit'
  pod 'Masonry'
  pod 'YYKit'
  pod 'MJRefresh'
  pod ‘MBProgressHUD’
  pod ‘WMPageController’
  pod ‘iCarousel’
  pod ‘MLTransition’
  pod ‘UITableView+FDTemplateLayoutCell’

end
